using Microsoft.Extensions.Logging;
using Moq;
using SchemaForge.Abstractions.Interfaces;
using SchemaForge.Abstractions.Models;
using SchemaForge.Providers.Oracle;
using SchemaForge.Services;
using SchemaForge.Tests.Helpers;

namespace SchemaForge.Tests;

public class OracleSchemaWriterTests
{
    private readonly SqlCollector _sqlCollector = new(isCollecting: true);
    private readonly SnakeCaseConverter _namingConverter = TestServices.CreateSnakeCaseConverter("oracle");
    private readonly UniversalDataTypeMapper _dataTypeMapper = TestServices.CreateDataTypeMapper();
    private readonly SqlDialectConverter _dialectConverter = new();
    private readonly OracleSchemaWriter _writer;

    public OracleSchemaWriterTests()
    {
        _writer = new OracleSchemaWriter(
            Mock.Of<ILogger<OracleSchemaWriter>>(),
            _namingConverter,
            _dataTypeMapper,
            _dialectConverter,
            _sqlCollector);
    }

    [Fact]
    public async Task CreateSchemaAsync_CreatesTableWithDoubleQuoteQuoting()
    {
        var tables = new List<TableSchema>
        {
            TestData.Table("Users", "dbo",
                columns: [TestData.Column("Id", "int", identity: true), TestData.Column("Name", "nvarchar", maxLength: 100)],
                primaryKeys: ["Id"])
        };

        await _writer.CreateSchemaAsync("", "MYSCHEMA", tables);

        var tableSql = _sqlCollector.GetStatements().First(s => s.Category == "Tables").Sql;
        Assert.Contains("\"MYSCHEMA\".\"USERS\"", tableSql);
        Assert.Contains("\"ID\"", tableSql);
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", tableSql);
        Assert.Contains("\"pk_USERS\"", tableSql);
    }

    [Fact]
    public async Task CreateSchemaAsync_CreatesForeignKeys()
    {
        var tables = new List<TableSchema>
        {
            TestData.Table("Orders", "dbo",
                columns: [TestData.Column("Id", "int"), TestData.Column("UserId", "int")],
                primaryKeys: ["Id"],
                foreignKeys: [TestData.ForeignKey("FK_Orders_Users", "UserId", "Users", "Id")])
        };

        await _writer.CreateSchemaAsync("", "MYSCHEMA", tables);

        var fkStmt = _sqlCollector.GetStatements().First(s => s.Category == "ForeignKeys");
        Assert.Contains("FOREIGN KEY", fkStmt.Sql);
        Assert.Contains("REFERENCES", fkStmt.Sql);
    }

    [Fact]
    public async Task CreateIndexesAsync_CreatesBasicIndex()
    {
        var indexes = new List<IndexSchema>
        {
            TestData.Index("IX_Users_Name", "Users", columns: "Name")
        };

        await _writer.CreateIndexesAsync("", "MYSCHEMA", indexes);

        var stmt = _sqlCollector.GetStatements().First(s => s.Category == "Indexes");
        Assert.Contains("CREATE INDEX", stmt.Sql);
        Assert.Contains("\"MYSCHEMA\"", stmt.Sql);
    }

    [Fact]
    public async Task CreateIndexesAsync_CreatesUniqueIndex()
    {
        var indexes = new List<IndexSchema>
        {
            TestData.Index("IX_Users_Email", "Users", isUnique: true, columns: "Email")
        };

        await _writer.CreateIndexesAsync("", "MYSCHEMA", indexes);

        var stmt = _sqlCollector.GetStatements().First(s => s.Category == "Indexes");
        Assert.Contains("CREATE UNIQUE INDEX", stmt.Sql);
    }

    [Fact]
    public async Task CreateIndexesAsync_SkipsPrimaryKeyIndexes()
    {
        var indexes = new List<IndexSchema>
        {
            TestData.Index("PK_Users", "Users", isPrimaryKey: true, columns: "Id")
        };

        await _writer.CreateIndexesAsync("", "MYSCHEMA", indexes);

        Assert.DoesNotContain(_sqlCollector.GetStatements(), s => s.Category == "Indexes");
    }

    [Fact]
    public async Task CreateConstraintsAsync_CreatesCheckConstraint()
    {
        var constraints = new List<ConstraintSchema>
        {
            TestData.Constraint("CK_Users_Age", "Users", "dbo", ConstraintType.Check,
                columns: ["Age"], checkExpression: "[Age] >= 0")
        };

        await _writer.CreateConstraintsAsync("", "MYSCHEMA", constraints);

        var stmt = _sqlCollector.GetStatements().First(s => s.Category == "Constraints");
        Assert.Contains("CHECK", stmt.Sql);
    }

    [Fact]
    public async Task CreateConstraintsAsync_CreatesUniqueConstraint()
    {
        var constraints = new List<ConstraintSchema>
        {
            TestData.Constraint("UQ_Users_Email", "Users", "dbo", ConstraintType.Unique,
                columns: ["Email"])
        };

        await _writer.CreateConstraintsAsync("", "MYSCHEMA", constraints);

        var stmt = _sqlCollector.GetStatements().First(s => s.Category == "Constraints");
        Assert.Contains("UNIQUE", stmt.Sql);
    }

    [Fact]
    public async Task CreateConstraintsAsync_CreatesDefaultConstraint()
    {
        var constraints = new List<ConstraintSchema>
        {
            TestData.Constraint("DF_Users_CreatedAt", "Users", "dbo", ConstraintType.Default,
                columns: ["CreatedAt"], defaultExpression: "(GETDATE())")
        };

        await _writer.CreateConstraintsAsync("", "MYSCHEMA", constraints);

        var stmt = _sqlCollector.GetStatements().First(s => s.Category == "Constraints");
        Assert.Contains("MODIFY", stmt.Sql);
        Assert.Contains("DEFAULT", stmt.Sql);
        Assert.Contains("SYSDATE", stmt.Sql);
    }

    [Fact]
    public async Task CreateViewsAsync_CreatesView()
    {
        var views = new List<ViewSchema>
        {
            TestData.View("ActiveUsers", "dbo", "SELECT Id, Name FROM Users WHERE IsActive = 1")
        };

        await _writer.CreateViewsAsync("", "MYSCHEMA", views);

        var stmt = _sqlCollector.GetStatements().First(s => s.Category == "Views");
        Assert.Contains("CREATE OR REPLACE VIEW", stmt.Sql);
    }
}
