using Microsoft.Extensions.Logging;
using Moq;
using SchemaForge.Abstractions.Interfaces;
using SchemaForge.Abstractions.Models;
using SchemaForge.Providers.Postgres;
using SchemaForge.Services;
using SchemaForge.Tests.Helpers;

namespace SchemaForge.Tests;

public class PostgresSchemaWriterTests
{
    private readonly SqlCollector _sqlCollector = new(isCollecting: true);
    private readonly SnakeCaseConverter _namingConverter = TestServices.CreateSnakeCaseConverter();
    private readonly UniversalDataTypeMapper _dataTypeMapper = TestServices.CreateDataTypeMapper();
    private readonly SqlDialectConverter _dialectConverter = new();
    private readonly PostgresSchemaWriter _writer;

    public PostgresSchemaWriterTests()
    {
        _writer = new PostgresSchemaWriter(
            Mock.Of<ILogger<PostgresSchemaWriter>>(),
            _namingConverter,
            _dataTypeMapper,
            _dialectConverter,
            _sqlCollector);
    }

    [Fact]
    public async Task CreateSchemaAsync_CreatesTable_WithCorrectSql()
    {
        var tables = new List<TableSchema>
        {
            TestData.Table("Users", "dbo",
                columns: [TestData.Column("Id", "int", identity: true), TestData.Column("Name", "nvarchar", maxLength: 100)],
                primaryKeys: ["Id"])
        };

        await _writer.CreateSchemaAsync("", "public", tables);

        var statements = _sqlCollector.GetStatements();
        var tableSql = statements.First(s => s.Category == "Tables").Sql;
        Assert.Contains("CREATE TABLE IF NOT EXISTS public.\"users\"", tableSql);
        Assert.Contains("\"id\"", tableSql);
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", tableSql);
        Assert.Contains("NOT NULL", tableSql);
        Assert.Contains("pk_users", tableSql);
    }

    [Fact]
    public async Task CreateSchemaAsync_CreatesForeignKeys()
    {
        var tables = new List<TableSchema>
        {
            TestData.Table("Orders", "dbo",
                columns: [TestData.Column("Id", "int"), TestData.Column("UserId", "int")],
                primaryKeys: ["Id"],
                foreignKeys: [TestData.ForeignKey("FK_Orders_Users", "UserId", "Users", "Id")])
        };

        await _writer.CreateSchemaAsync("", "public", tables);

        var fkStmt = _sqlCollector.GetStatements().First(s => s.Category == "ForeignKeys");
        Assert.Contains("ADD CONSTRAINT", fkStmt.Sql);
        Assert.Contains("FOREIGN KEY", fkStmt.Sql);
        Assert.Contains("REFERENCES", fkStmt.Sql);
    }

    [Fact]
    public async Task CreateSchemaAsync_NonPublicSchema_CreatesSchemaFirst()
    {
        var tables = new List<TableSchema>
        {
            TestData.Table("Users", "dbo",
                columns: [TestData.Column("Id", "int")],
                primaryKeys: ["Id"])
        };

        await _writer.CreateSchemaAsync("", "custom", tables);

        var schemaStmt = _sqlCollector.GetStatements().First(s => s.Category == "Schema");
        Assert.Contains("CREATE SCHEMA IF NOT EXISTS", schemaStmt.Sql);
    }

    [Fact]
    public async Task CreateSchemaAsync_PublicSchema_SkipsSchemaCreation()
    {
        var tables = new List<TableSchema>
        {
            TestData.Table("Users", "dbo",
                columns: [TestData.Column("Id", "int")],
                primaryKeys: ["Id"])
        };

        await _writer.CreateSchemaAsync("", "public", tables);

        Assert.DoesNotContain(_sqlCollector.GetStatements(), s => s.Category == "Schema");
    }

    [Fact]
    public async Task CreateIndexesAsync_CreatesBasicIndex()
    {
        var indexes = new List<IndexSchema>
        {
            TestData.Index("IX_Users_Name", "Users", isUnique: false, columns: "Name")
        };

        await _writer.CreateIndexesAsync("", "public", indexes);

        var stmt = _sqlCollector.GetStatements().First(s => s.Category == "Indexes");
        Assert.Contains("CREATE INDEX", stmt.Sql);
        Assert.Contains("\"ix_users_name\"", stmt.Sql);
        Assert.DoesNotContain("UNIQUE", stmt.Sql);
    }

    [Fact]
    public async Task CreateIndexesAsync_CreatesUniqueIndex()
    {
        var indexes = new List<IndexSchema>
        {
            TestData.Index("IX_Users_Email", "Users", isUnique: true, columns: "Email")
        };

        await _writer.CreateIndexesAsync("", "public", indexes);

        var stmt = _sqlCollector.GetStatements().First(s => s.Category == "Indexes");
        Assert.Contains("CREATE UNIQUE INDEX", stmt.Sql);
    }

    [Fact]
    public async Task CreateIndexesAsync_WithIncludedColumns()
    {
        var indexes = new List<IndexSchema>
        {
            TestData.IndexWithInclude("IX_Users_Name", "Users", "dbo",
                isUnique: false,
                columns: ["Name"],
                includedColumns: ["Email"])
        };

        await _writer.CreateIndexesAsync("", "public", indexes);

        var stmt = _sqlCollector.GetStatements().First(s => s.Category == "Indexes");
        Assert.Contains("INCLUDE", stmt.Sql);
        Assert.Contains("\"email\"", stmt.Sql);
    }

    [Fact]
    public async Task CreateIndexesAsync_WithFilterExpression()
    {
        var indexes = new List<IndexSchema>
        {
            TestData.Index("IX_Users_Active", "Users", filterExpression: "[IsActive] = 1", columns: "Name")
        };

        await _writer.CreateIndexesAsync("", "public", indexes);

        var stmt = _sqlCollector.GetStatements().First(s => s.Category == "Indexes");
        Assert.Contains("WHERE", stmt.Sql);
    }

    [Fact]
    public async Task CreateIndexesAsync_SkipsPrimaryKeyIndexes()
    {
        var indexes = new List<IndexSchema>
        {
            TestData.Index("PK_Users", "Users", isPrimaryKey: true, columns: "Id")
        };

        await _writer.CreateIndexesAsync("", "public", indexes);

        Assert.DoesNotContain(_sqlCollector.GetStatements(), s => s.Category == "Indexes");
    }

    [Fact]
    public async Task CreateConstraintsAsync_CreatesCheckConstraint()
    {
        var constraints = new List<ConstraintSchema>
        {
            TestData.Constraint("CK_Users_Age", "Users", "dbo", ConstraintType.Check,
                columns: ["Age"], checkExpression: "[Age] >= 0")
        };

        await _writer.CreateConstraintsAsync("", "public", constraints);

        var stmt = _sqlCollector.GetStatements().First(s => s.Category == "Constraints");
        Assert.Contains("CHECK", stmt.Sql);
        Assert.Contains("\"age\" >= 0", stmt.Sql);
    }

    [Fact]
    public async Task CreateConstraintsAsync_ConvertsSalaryCheckConstraint()
    {
        var constraints = new List<ConstraintSchema>
        {
            TestData.Constraint("CK_Employees_Salary", "Employees", "dbo", ConstraintType.Check,
                columns: ["Salary"], checkExpression: "CHECK (Salary >= 0)")
        };

        await _writer.CreateConstraintsAsync("", "public", constraints);

        var stmt = _sqlCollector.GetStatements().First(s => s.Category == "Constraints");
        Assert.Contains("CHECK", stmt.Sql);
        Assert.Contains("\"salary\" >= 0", stmt.Sql);
        Assert.DoesNotContain("Salary", stmt.Sql); // Ensure uppercase is not present
    }

    [Fact]
    public async Task CreateConstraintsAsync_CreatesUniqueConstraint()
    {
        var constraints = new List<ConstraintSchema>
        {
            TestData.Constraint("UQ_Users_Email", "Users", "dbo", ConstraintType.Unique,
                columns: ["Email"])
        };

        await _writer.CreateConstraintsAsync("", "public", constraints);

        var stmt = _sqlCollector.GetStatements().First(s => s.Category == "Constraints");
        Assert.Contains("UNIQUE", stmt.Sql);
        Assert.Contains("\"email\"", stmt.Sql);
    }

    [Fact]
    public async Task CreateConstraintsAsync_CreatesDefaultConstraint()
    {
        var constraints = new List<ConstraintSchema>
        {
            TestData.Constraint("DF_Users_CreatedAt", "Users", "dbo", ConstraintType.Default,
                columns: ["CreatedAt"], defaultExpression: "(GETDATE())")
        };

        await _writer.CreateConstraintsAsync("", "public", constraints);

        var stmt = _sqlCollector.GetStatements().First(s => s.Category == "Constraints");
        Assert.Contains("SET DEFAULT", stmt.Sql);
        Assert.Contains("NOW()", stmt.Sql);
    }

    [Fact]
    public async Task CreateConstraintsAsync_BooleanDefaultConversion()
    {
        var constraints = new List<ConstraintSchema>
        {
            TestData.Constraint("DF_Users_IsActive", "Users", "dbo", ConstraintType.Default,
                columns: ["IsActive"], defaultExpression: "((1))", columnDataType: "bit")
        };

        await _writer.CreateConstraintsAsync("", "public", constraints);

        var stmt = _sqlCollector.GetStatements().First(s => s.Category == "Constraints");
        Assert.Contains("TRUE", stmt.Sql);
    }

    [Fact]
    public async Task CreateViewsAsync_CreatesViewWithConvertedDefinition()
    {
        var views = new List<ViewSchema>
        {
            TestData.View("ActiveUsers", "dbo", "SELECT [Id], [Name] FROM [Users] WHERE [IsActive] = 1")
        };

        await _writer.CreateViewsAsync("", "public", views);

        var stmt = _sqlCollector.GetStatements().First(s => s.Category == "Views");
        Assert.Contains("CREATE OR REPLACE VIEW", stmt.Sql);
        Assert.Contains("\"Id\"", stmt.Sql);
    }
}
